version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: campus-games-postgres
    restart: always
    environment:
      POSTGRES_USER: campus_admin
      POSTGRES_PASSWORD: CampusAdmin2025!
      POSTGRES_DB: campus_games
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d

  pgadmin:
    image: dpage/pgadmin4
    container_name: campus-games-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@campus.games
      PGADMIN_DEFAULT_PASSWORD: CampusPgAdmin2025!
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  pgadmin_data:
